# Generated by Django 5.2.6 on 2025-09-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
