# Generated by Django 5.2.6 on 2025-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='communication_address',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
