# Generated by Django 5.2.6 on 2025-11-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0002_customer_communication_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='communication_address',
            new_name='communication_phone',
        ),
    ]
