# Generated by Django 5.2.6 on 2025-11-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0003_rename_communication_address_customer_communication_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-is_default']},
        ),
    ]
